spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-services-security-microservices

  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**


server:
  port: 9000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls[0]:
       name: Product Service
       url: /aggregate/product-service/v1/api-docs
    urls[1]:
      name: Order Service
      url: /aggregate/order-service/v1/api-docs
    urls[2]:
      name: Inventory Service
      url: /aggregate/inventory-service/v1/api-docs



routes:
  url:
    product-service: http://localhost:1662
    order-service: http://localhost:1663
    inventory-service: http://localhost:1664

##actuator endpoints!
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true


##resilience4j endpoints!

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-type: count_based
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        minimum-number-of-calls: 5

  ##resilience4j timeout properties
  timelimiter:
    configs:
      default:
        timeout-duration:
          seconds: 3
  ##resilience4j retry properties
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration:
          seconds: 2



